package com.app.entero.direct.database.models;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig AddtoCartDaoConfig;

    private final AddtoCartDao AddtoCartDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        AddtoCartDaoConfig = daoConfigMap.get(AddtoCartDao.class).clone();
        AddtoCartDaoConfig.initIdentityScope(type);

        AddtoCartDao = new AddtoCartDao(AddtoCartDaoConfig, this);

        registerDao(AddToCart.class, AddtoCartDao);
    }
    
    public void clear() {
        AddtoCartDaoConfig.clearIdentityScope();
    }

    public AddtoCartDao getAddtoCartDao() {
        return AddtoCartDao;
    }

}
